name: Unity CI — Build ISLA (Windows only)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Windows (StandaloneWindows64)
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('Packages/manifest.json', 'ProjectSettings/ProjectVersion.txt') }}
          restore-keys: |
            Library-${{ runner.os }}-
            Library-

      - name: Verify license secrets
        shell: bash
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_SERIAL:  ${{ secrets.UNITY_SERIAL }}
        run: |
          if [ -z "${UNITY_LICENSE:-}" ] && [ -z "${UNITY_SERIAL:-}" ]; then
            echo "❌ Missing license: set UNITY_LICENSE (ULF) or UNITY_SERIAL (+ UNITY_EMAIL + UNITY_PASSWORD)."
            exit 1
          fi
          echo "✅ License secret detected."

      - name: Build project (Windows)
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE:  ${{ secrets.UNITY_LICENSE }}
          UNITY_SERIAL:   ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL:    ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          unityVersion: auto
          buildName: ISLA
          buildsPath: build
          allowDirtyBuild: true

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ISLA-Windows64
          path: build/StandaloneWindows64
